In [1]:
import tensorflow as tf
import keras

2025-05-08 19:14:22.410239: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-08 19:14:22.411284: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-08 19:14:22.431691: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-08 19:14:22.432054: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
layer = keras.layers.GRU(1, stateful=True)
layers_s = keras.layers.GRU(2, return_sequences=True, return_state=True)

2025-05-08 19:14:48.953432: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-05-08 19:14:48.953451: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: 9c0a971006ac
2025-05-08 19:14:48.953455: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: 9c0a971006ac
2025-05-08 19:14:48.953489: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 570.133.7
2025-05-08 19:14:48.953497: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 570.133.7
2025-05-08 19:14:48.953500: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:309] kernel version seems to match DSO: 570.133.7


In [3]:
tokens = tf.constant([[1, 2.1, 3, 4], [1, 2, 3, 4], [0, 2, 3, 4]])
print(tokens.shape)
inp_tensor = tf.reshape(tokens, (1, 3, 4))
print(layer(inp_tensor))

(3, 4)
tf.Tensor([[-0.463429]], shape=(1, 1), dtype=float32)


In [4]:
print(layers_s(inp_tensor))

[<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[0.08749311, 0.57524586],
        [0.17843355, 0.8247869 ],
        [0.31418216, 0.8517587 ]]], dtype=float32)>, <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.31418216, 0.8517587 ]], dtype=float32)>]


In [5]:
(output, state) = layers_s(inp_tensor)
print(output)
print(state)

tf.Tensor(
[[[0.08749311 0.57524586]
  [0.17843355 0.8247869 ]
  [0.31418216 0.8517587 ]]], shape=(1, 3, 2), dtype=float32)
tf.Tensor([[0.31418216 0.8517587 ]], shape=(1, 2), dtype=float32)
